name: docfx for GitHub Pages

on:
  push:
    branches:
      - 'main'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove csproj files
        run: find . -name "*.csproj" -type f -delete

      - name: Deploy with DocFX
        uses: sator-imaging/docfx-pages@v1.7.1
        id: deployment
        with:
          app_name: 'Save System For Unity'
          site_title: 'Save System For Unity'
          site_footer: '<big>&times;Maintained By Studio-23</big>'
          class_members: 'separatePages'
          google_analytics: ''
          define_symbols: ''
          site_logo: 'https://raw.githubusercontent.com/Studio-23-xyz/studio23-website/refs/heads/main/public/assets/studio_23_logo.svg'
          site_favicon: 'https://raw.githubusercontent.com/Studio-23-xyz/studio23-website/refs/heads/main/public/assets/studio_23_logo.svg'
          main_js: |
            export default {
                defaultTheme: 'light',
                showLightbox: (img) => true,
                iconLinks: [
                    {
                        icon: 'github',
                        href: 'https://github.com/sator-imaging',
                        title: 'GitHub'
                    },
                ],
            }
          main_css: |
