name: InspectCode

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
  
jobs:
  inspect-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Annotate
        # You may pin to the exact commit or the version.
        uses: JetBrains/ReSharper-InspectCode@v0.3
        with:
          solution: ./SaveSystem.sln
          format: Html
          output: ./Report/index.html
    permissions:
      security-events: write
      
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results
          path: ./Report/index.html