name: InspectMaster

on:
  push:
    branches: [ main ]

jobs:
  self-test:
   runs-on: ubuntu-latest
   name: Self Test
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Inspect
       uses: florius0/resharper-unity-ci
       with:
          solution: './SaveSystem.sln'